In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

C:\Users\Admin\AppData\Local\Temp\ipykernel_22868\1748781244.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [5]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [6]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [7]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [8]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [9]:
books.duplicated().sum()

0

In [12]:
users.duplicated().sum()

0

In [13]:
ratings.duplicated().sum()

0

## popularity based recommendation system

In [15]:
rate_with_name = ratings.merge(books, on='ISBN')

In [17]:
rate_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [23]:
num_rating_df = rate_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_rating'},inplace=True)

In [24]:
num_rating_df

                                               Book-Title  num_rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.           2
241067                     Ã?Â?rger mit Produkt X. Roman.           4
241068                                Ã?Â?sterlich leben.           1
241069                              Ã?Â?stlich der Berge.           3
241070                                  Ã?Â?thique en toc           2

[241071 rows x 2 columns]

In [25]:
avg_rating_df = rate_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)

In [26]:
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [28]:
popular_df = num_rating_df.merge(avg_rating_df, on='Book-Title')

In [29]:
popular_df

,Book-Title,num_rating,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [37]:
popular_df = popular_df[popular_df['num_rating'] >= 250].sort_values('avg_rating',ascending=False).head(50)

In [38]:
popular_df

,Book-Title,num_rating,avg_rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [45]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_rating','avg_rating']]

In [46]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num_rating,avg_rating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

# collabarative based recommendation system

In [47]:
rate_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [53]:
x = rate_with_name.groupby('User-ID').count()['Book-Rating'] > 250
rated_users=x[x].index

In [58]:
filterd_rating = rate_with_name[rate_with_name['User-ID'].isin(rated_users)]

In [66]:
y = filterd_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = y[y].index

In [71]:
final_ratings = filterd_rating[filterd_rating['Book-Title'].isin(famous_books)]
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1025422,264317,0833563505,0,The Queen of the Damned (Vampire Chronicles (P...,Anne Rice,1999,Sagebrush Bound,http://images.amazon.com/images/P/0833563505.0...,http://images.amazon.com/images/P/0833563505.0...,http://images.amazon.com/images/P/0833563505.0...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [74]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [76]:
pt.fillna(0,inplace=True)

In [77]:
pt

User-ID,254,2276,2766,3363,4385,6251,6543,6575,7158,7346,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wuthering Heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [78]:
from sklearn.metrics.pairwise import cosine_similarity

In [80]:
s_score = cosine_similarity(pt)

In [82]:
s_score.shape

(574, 574)

In [88]:
s_score[1]

array([0.12637786, 1.        , 0.28824811, 0.        , 0.11125827,
       0.11563932, 0.14829437, 0.22646551, 0.06177397, 0.0885607 ,
       0.21788538, 0.11613742, 0.13213286, 0.10517688, 0.06045376,
       0.1141112 , 0.18893964, 0.06217966, 0.17831323, 0.06858781,
       0.12981502, 0.        , 0.10383166, 0.09180577, 0.08413906,
       0.043249  , 0.10246172, 0.05546267, 0.22848533, 0.05432112,
       0.23689829, 0.07156785, 0.34898415, 0.04778995, 0.07742281,
       0.05565811, 0.03249572, 0.16237882, 0.02725355, 0.07832632,
       0.06353868, 0.07167959, 0.08444546, 0.06214241, 0.        ,
       0.21949514, 0.09072713, 0.        , 0.12247009, 0.04991835,
       0.12205811, 0.        , 0.03213976, 0.25798204, 0.10220593,
       0.05318361, 0.09100778, 0.14064629, 0.0171898 , 0.11837654,
       0.11589455, 0.1169941 , 0.15731228, 0.10010149, 0.19162691,
       0.10465973, 0.09444324, 0.08627589, 0.        , 0.01849475,
       0.16123608, 0.05733041, 0.12059457, 0.        , 0.12195497,
       0.06863692, 0.24319759, 0.18176762, 0.13567542, 0.09749588,
       0.14650888, 0.10106344, 0.18177405, 0.12174135, 0.10327632,
       0.11638179, 0.06417775, 0.04377878, 0.13839313, 0.08473322,
       0.14160842, 0.11717904, 0.10816476, 0.26493918, 0.        ,
       0.25293055, 0.11301115, 0.10353285, 0.11730323, 0.13966293,
       0.21344409, 0.08370571, 0.14967936, 0.0384717 , 0.08643235,
       0.0451476 , 0.1535089 , 0.06790134, 0.08009578, 0.20148842,
       0.07420868, 0.21370725, 0.1417206 , 0.21422601, 0.14939587,
       0.1326455 , 0.09264405, 0.14245474, 0.14678993, 0.13508317,
       0.06056223, 0.17726058, 0.07793869, 0.        , 0.17892283,
       0.18616687, 0.18292332, 0.1633523 , 0.07164305, 0.1033477 ,
       0.13003189, 0.12953824, 0.04524829, 0.11872727, 0.14340798,
       0.04472379, 0.14304824, 0.10071708, 0.10779081, 0.09933805,
       0.10463066, 0.11607213, 0.19498294, 0.17089017, 0.17592188,
       0.        , 0.2185097 , 0.05630959, 0.24701598, 0.06279982,
       0.23654799, 0.09310913, 0.21448244, 0.06373398, 0.07148439,
       0.23313507, 0.0654633 , 0.19677216, 0.15872412, 0.15165577,
       0.17272727, 0.10318014, 0.        , 0.14223871, 0.14115976,
       0.08760659, 0.07568682, 0.02844061, 0.08832295, 0.18662147,
       0.13356165, 0.05272738, 0.17358988, 0.14666095, 0.11394053,
       0.07915147, 0.12095025, 0.02944764, 0.0563225 , 0.03111796,
       0.08789645, 0.13324751, 0.16973256, 0.12819667, 0.        ,
       0.18253119, 0.16052066, 0.31916551, 0.15750974, 0.23168921,
       0.16369295, 0.        , 0.06567993, 0.24625452, 0.1814416 ,
       0.03670676, 0.18263451, 0.03042629, 0.04014053, 0.15063   ,
       0.12914285, 0.16056213, 0.19438444, 0.11029542, 0.09964402,
       0.19285166, 0.03768657, 0.16192102, 0.08813139, 0.04713162,
       0.15584861, 0.05351573, 0.13556472, 0.09942561, 0.13457883,
       0.06822904, 0.        , 0.12172072, 0.26418351, 0.07935757,
       0.02780269, 0.13342533, 0.1622197 , 0.06681769, 0.12658275,
       0.1054889 , 0.13978103, 0.13019337, 0.09792203, 0.16722113,
       0.24210353, 0.20327724, 0.0983709 , 0.06981926, 0.07497346,
       0.05384389, 0.16484665, 0.20069007, 0.15873114, 0.27981747,
       0.10263834, 0.07612865, 0.07648368, 0.08535654, 0.20537747,
       0.17426276, 0.17142791, 0.        , 0.08808885, 0.0458676 ,
       0.14665949, 0.06362781, 0.07681964, 0.14772133, 0.04976379,
       0.        , 0.1239099 , 0.1216915 , 0.10208236, 0.10838008,
       0.11625   , 0.0472202 , 0.12869078, 0.05987084, 0.11723497,
       0.06096171, 0.1763439 , 0.11454499, 0.16494859, 0.08686916,
       0.07376037, 0.04764339, 0.15519285, 0.16655642, 0.05919477,
       0.14408746, 0.25062807, 0.10324942, 0.09448599, 0.32459428,
       0.12334338, 0.12864454, 0.1023519 , 0.2793063 , 0.05741549,
       0.08548735, 0.05080286, 0.15489693, 0.04790854, 0.05491268,
       0.14042443, 0.13826912, 0.03975708, 0.16758481, 0.03942947,
       0.0389738 , 0.06678352, 0.10788653, 0.1047206 , 0.36141566,
       0.19260065, 0.11722178, 0.11786576, 0.20033279, 0.1572727 ,
       0.05346092, 0.12955129, 0.22044188, 0.14184272, 0.04721552,
       0.06337755, 0.06173217, 0.25532514, 0.08164835, 0.10321666,
       0.07602816, 0.04595097, 0.07557185, 0.32408557, 0.08635077,
       0.1070795 , 0.09775331, 0.08366069, 0.09047704, 0.09374569,
       0.14088698, 0.09222911, 0.09480916, 0.08693184, 0.04306492,
       0.06434954, 0.04124128, 0.17006744, 0.08744373, 0.23015358,
       0.12830246, 0.06521044, 0.05087427, 0.07366297, 0.09228197,
       0.05653697, 0.07869681, 0.17679645, 0.05686607, 0.17010028,
       0.06759571, 0.06094826, 0.06353732, 0.2312445 , 0.06240355,
       0.1582188 , 0.1104428 , 0.05246409, 0.13838444, 0.07520106,
       0.13400371, 0.09703441, 0.15559166, 0.10109468, 0.10570418,
       0.06437423, 0.18451664, 0.13008494, 0.05623368, 0.1421696 ,
       0.04579441, 0.        , 0.09808241, 0.        , 0.19566199,
       0.05048829, 0.10178673, 0.11632749, 0.14366418, 0.07781285,
       0.02023776, 0.12644935, 0.07235452, 0.09183752, 0.2057754 ,
       0.05140729, 0.        , 0.16145079, 0.09965953, 0.10897508,
       0.07006088, 0.09027103, 0.02496749, 0.        , 0.        ,
       0.11355647, 0.10674805, 0.09217808, 0.0756555 , 0.02869762,
       0.08428843, 0.16632614, 0.15099907, 0.04005119, 0.14540937,
       0.24968402, 0.04099254, 0.1187371 , 0.09893768, 0.24141031,
       0.04421694, 0.1140071 , 0.081641  , 0.17481366, 0.22817252,
       0.12787909, 0.13299265, 0.07800366, 0.07271813, 0.1166956 ,
       0.10608419, 0.14909624, 0.08895019, 0.13834238, 0.16880997,
       0.14598167, 0.16453139, 0.10516739, 0.08110148, 0.12690582,
       0.11890404, 0.14293946, 0.04383454, 0.03233538, 0.0468775 ,
       0.06185925, 0.15646027, 0.05623249, 0.10163807, 0.05585346,
       0.        , 0.14586318, 0.04328447, 0.0818083 , 0.08778301,
       0.18020792, 0.12925519, 0.0420615 , 0.04485087, 0.0481196 ,
       0.13169707, 0.07280612, 0.10127542, 0.08206163, 0.10882644,
       0.10206293, 0.12287444, 0.18359677, 0.05042849, 0.10279825,
       0.11054938, 0.15882202, 0.        , 0.01401547, 0.04865795,
       0.06844574, 0.13605594, 0.10844147, 0.0731957 , 0.02022235,
       0.13541058, 0.19210853, 0.17480271, 0.09197118, 0.        ,
       0.11802065, 0.10930042, 0.19596821, 0.0354119 , 0.11886677,
       0.05871682, 0.12297505, 0.03512297, 0.13265577, 0.13648269,
       0.11456398, 0.16414125, 0.07208529, 0.05380277, 0.16479002,
       0.10184237, 0.04319302, 0.10613623, 0.10935328, 0.10104032,
       0.07870883, 0.15048829, 0.0866867 , 0.22339223, 0.13314818,
       0.11514214, 0.00439537, 0.09523623, 0.17039955, 0.        ,
       0.25193925, 0.15196003, 0.29698694, 0.12082115, 0.10197213,
       0.1441458 , 0.05434891, 0.10702941, 0.06664726, 0.19131675,
       0.10054299, 0.08859659, 0.02038855, 0.20683711, 0.05198553,
       0.12884828, 0.08930155, 0.05133082, 0.0649182 , 0.06935463,
       0.10708562, 0.19167691, 0.13940888, 0.0516619 , 0.07239977,
       0.24358538, 0.09571273, 0.08793525, 0.10258512, 0.10620008,
       0.16725129, 0.14523478, 0.1150115 , 0.14544756, 0.1352729 ,
       0.27705771, 0.07755856, 0.15335346, 0.10623352, 0.2402767 ,
       0.12157623, 0.32028672, 0.08597817, 0.09200734, 0.04564908,
       0.16807458, 0.20193788, 0.04351307, 0.06340596, 0.1805317 ,
       0.11080939, 0.04764585, 0.14218643, 0.        , 0.15329697,
       0.18307169, 0.02757598, 0.04417832, 0.22631979, 0.06763171,
       0.14439383, 0.11664251, 0.08543548, 0.08931256, 0.09266639,
       0.08966957, 0.08014539, 0.10950786, 0.16577006, 0.07005512,
       0.20773083, 0.08010424, 0.18117097, 0.1617243 ])

In [99]:
def recommend(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_item = sorted(list(enumerate(s_score[index])),key=lambda x:x[1],reverse=True)[1:6]
    
    for i in similar_item:
        print(pt.index[i[0]])

In [100]:
recommend('1984')

The Handmaid's Tale
The Vampire Lestat (Vampire Chronicles, Book II)
The Hours : A Novel
Brave New World
The Bonesetter's Daughter

In [105]:
recommend('The Rainmaker')

The Firm
The Chamber
The Partner
The Pelican Brief
The Client